EXTENSION_TO_LANGUAGE: dict[str, str] = {
    ".py": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
    ".java": "Java",
    ".kt": "Kotlin",
    ".swift": "Swift",
    ".go": "Go",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".cxx": "C++",
    ".hpp": "C++",
    ".cs": "C#",
    ".scala": "Scala",
    ".html": "HTML",
    ".htm": "HTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".less": "Less",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".dart": "Dart",
    ".r": "R",
    ".R": "R",
    ".m": "Objective-C",
    ".lua": "Lua",
    ".pl": "Perl",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".ps1": "PowerShell",
    ".sql": "SQL",
    ".tf": "Terraform",
    ".yml": "YAML",
    ".yaml": "YAML",
    ".json": "JSON",
    ".xml": "XML",
    ".md": "Markdown",
    ".dockerfile": "Docker",
    ".ex": "Elixir",
    ".exs": "Elixir",
    ".erl": "Erlang",
    ".hs": "Haskell",
    ".ml": "OCaml",
    ".clj": "Clojure",
}

LANGUAGE_COLORS: dict[str, str] = {
    "Python": "#3572a5",
    "JavaScript": "#f7df1e",
    "TypeScript": "#3178c6",
    "Java": "#b07219",
    "Kotlin": "#a97bff",
    "Swift": "#f05138",
    "Go": "#00add8",
    "Rust": "#dea584",
    "Ruby": "#701516",
    "PHP": "#4f5d95",
    "C": "#555555",
    "C++": "#f34b7d",
    "C#": "#178600",
    "Scala": "#c22d40",
    "HTML": "#e34c26",
    "CSS": "#563d7c",
    "SCSS": "#c6538c",
    "Less": "#1d365d",
    "Vue": "#41b883",
    "Svelte": "#ff3e00",
    "Dart": "#00b4ab",
    "R": "#198ce7",
    "Objective-C": "#438eff",
    "Lua": "#000080",
    "Perl": "#0298c3",
    "Shell": "#89e051",
    "PowerShell": "#012456",
    "SQL": "#e38c00",
    "Terraform": "#5c4ee5",
    "YAML": "#cb171e",
    "JSON": "#292929",
    "XML": "#0060ac",
    "Markdown": "#083fa1",
    "Docker": "#384d54",
    "Elixir": "#6e4a7e",
    "Erlang": "#b83998",
    "Haskell": "#5e5086",
    "OCaml": "#3be133",
    "Clojure": "#db5855",
}


def detect_language(filename: str) -> str | None:
    """Return the language for a filename, or None if unrecognized."""
    import os
    _, ext = os.path.splitext(filename.lower())
    # Handle Dockerfile without extension
    if os.path.basename(filename).lower().startswith("dockerfile"):
        return "Docker"
    return EXTENSION_TO_LANGUAGE.get(ext)
